<#
.SYNOPSIS
Provisions Azure resources for Copilot trace monitoring and prepares collector environment.

.DESCRIPTION
Creates/updates a resource group deployment using azure-setup/infra/main.bicep and writes
azure-setup/collector/.env with the generated Application Insights connection string.

.PARAMETER SubscriptionId
Azure subscription ID used for deployment context.

.PARAMETER ResourceGroup
Target resource group name.

.PARAMETER Location
Azure region for resources. Defaults to eastus.

.PARAMETER NamePrefix
Prefix used to generate unique resource names. Defaults to copilottraces.

.PARAMETER DisableGrafanaRbac
If provided, disables automatic Monitoring Reader assignment for Managed Grafana.

.EXAMPLE
./azure-setup/scripts/provision.ps1 -SubscriptionId "<sub-id>" -ResourceGroup "rg-copilot-traces"

.EXAMPLE
./azure-setup/scripts/provision.ps1 -SubscriptionId "<sub-id>" -ResourceGroup "rg-copilot-traces" -Location "westeurope" -NamePrefix "teamx"
#>
param(
  [Parameter(Mandatory = $true)]
  [string]$SubscriptionId,

  [Parameter(Mandatory = $true)]
  [string]$ResourceGroup,

  [string]$Location = "eastus",
  [string]$NamePrefix = "copilottraces",
  [switch]$DisableGrafanaRbac
)

$ErrorActionPreference = "Stop"

function Require-Command {
  param([string]$Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Required command '$Name' was not found in PATH."
  }
}

Write-Host "[1/7] Checking prerequisites..."
Require-Command "az"

Write-Host "[2/7] Ensuring Azure CLI authentication..."
$null = az account show --output none 2>$null
if ($LASTEXITCODE -ne 0) {
  az login | Out-Null
}

Write-Host "[3/7] Setting subscription context..."
az account set --subscription $SubscriptionId

Write-Host "[4/7] Ensuring Bicep is available..."
az bicep version | Out-Null
if ($LASTEXITCODE -ne 0) {
  az bicep install | Out-Null
}

Write-Host "[5/7] Creating resource group if missing..."
az group create --name $ResourceGroup --location $Location --output none

$normalizedPrefix = ($NamePrefix.ToLower() -replace '[^a-z0-9-]', '')
if ([string]::IsNullOrWhiteSpace($normalizedPrefix)) {
  $normalizedPrefix = "copilottraces"
}

$suffix = (Get-Random -Minimum 1000 -Maximum 9999)
$laName = "la-$normalizedPrefix-$suffix"
$appiName = "appi-$normalizedPrefix-$suffix"
$grafanaName = "amg-$normalizedPrefix-$suffix"
$deploymentName = "copilot-traces-infra-$suffix"

$assignGrafanaMonitoringReader = if ($DisableGrafanaRbac.IsPresent) { "false" } else { "true" }

Write-Host "[6/7] Deploying infrastructure..."
$deployment = az deployment group create `
  --resource-group $ResourceGroup `
  --name $deploymentName `
  --template-file "azure-setup/infra/main.bicep" `
  --parameters location=$Location `
               logAnalyticsWorkspaceName=$laName `
               appInsightsName=$appiName `
               grafanaName=$grafanaName `
               assignGrafanaMonitoringReader=$assignGrafanaMonitoringReader `
  --query properties.outputs `
  --output json | ConvertFrom-Json

if (-not $deployment) {
  throw "Deployment output was empty."
}

Write-Host "[7/7] Writing collector environment file..."
$collectorEnvPath = "azure-setup/collector/.env"
$connectionString = $deployment.appInsightsConnectionString.value

$envContent = @(
  "# Generated by azure-setup/scripts/provision.ps1"
  "OTEL_CONFIG_FILE=otel-collector-config.yaml"
  "COPILOT_USER_EMAIL="
  "APPINSIGHTS_CONNECTION_STRING=$connectionString"
  ""
  "# Fill these only when using preview OTLP ingestion mode"
  "AZURE_MONITOR_TRACES_ENDPOINT="
  "AZURE_MONITOR_LOGS_ENDPOINT="
  "AZURE_MONITOR_METRICS_ENDPOINT="
)

$envContent | Set-Content -Path $collectorEnvPath -Encoding UTF8

Write-Host ""
Write-Host "Provisioning complete."
Write-Host "Resource Group: $ResourceGroup"
Write-Host "Log Analytics: $($deployment.logAnalyticsWorkspaceResourceId.value)"
Write-Host "App Insights:  $($deployment.appInsightsResourceId.value)"
Write-Host "Grafana URL:   $($deployment.managedGrafanaEndpoint.value)"
Write-Host "Grafana MI:    $($deployment.managedGrafanaPrincipalId.value)"
Write-Host "Collector env: $collectorEnvPath"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1) Start collector: docker compose -f azure-setup/collector/docker-compose.yml up -d"
Write-Host "  2) Optional: set COPILOT_USER_EMAIL in $collectorEnvPath to stamp user identity on telemetry"
Write-Host "  2) Configure VS Code Copilot OTLP endpoint to http://localhost:4318"
Write-Host "  3) Open Managed Grafana and import GitHub Copilot dashboard"
